version: "2"
linters:
  default: all
  disable:
  - funcorder
  - depguard
  - exhaustruct
  - mnd
  - varnamelen
  settings:
    lll:
      line-length: 200
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - third_party$
    - builtin$
    - examples$
issues:
  fix: true
formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
